# Generated by Django 5.2.17 on 2026-08-13 12:54

import apps.profiles.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido, usando apenas números, espaços, parênteses, + ou -.', regex='^[0-9()+\\-\\s]{8,20}$')], verbose_name='telefone')),
                ('city', models.CharField(default='Avaré', max_length=100, verbose_name='cidade')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('bio', models.CharField(blank=True, help_text='Conte algo breve sobre você. Não inclua informações médicas.', max_length=300, verbose_name='breve apresentação')),
                ('photo', models.ImageField(blank=True, upload_to=apps.profiles.models.profile_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='foto de perfil')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil pessoal',
                'verbose_name_plural': 'perfis pessoais',
            },
        ),
    ]
