# Generated by Django 5.2.17 on 2026-08-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_accounts_user_email_ci_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Horário aproximado do último uso autenticado da plataforma.', null=True, verbose_name='última atividade em'),
        ),
    ]
