# Generated by Django 5.2.17 on 2026-08-13 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('report_review', 'Análise de denúncia'), ('professional_review', 'Análise de profissional'), ('user_status', 'Alteração de conta')], max_length=30, verbose_name='ação')),
                ('target_type', models.CharField(max_length=40, verbose_name='tipo do registro')),
                ('target_id', models.PositiveBigIntegerField(verbose_name='identificador do registro')),
                ('target_label', models.CharField(max_length=150, verbose_name='identificação resumida')),
                ('description', models.CharField(max_length=500, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='realizada em')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='administrador')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('behavior', 'Comportamento inadequado'), ('false_information', 'Informação possivelmente falsa'), ('privacy', 'Privacidade ou uso indevido de dados'), ('professional_profile', 'Perfil profissional'), ('technical', 'Problema técnico'), ('other', 'Outro assunto')], max_length=30, verbose_name='categoria')),
                ('subject', models.CharField(max_length=120, verbose_name='assunto')),
                ('description', models.TextField(max_length=1500, verbose_name='descrição')),
                ('status', models.CharField(choices=[('open', 'Recebida'), ('in_review', 'Em análise'), ('resolved', 'Resolvida'), ('dismissed', 'Encerrada sem ação')], default='open', max_length=20, verbose_name='status')),
                ('resolution_notes', models.TextField(blank=True, max_length=1000, verbose_name='retorno da administração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizada em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_assigned', to=settings.AUTH_USER_MODEL, verbose_name='responsável pela análise')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='usuário denunciado')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_created', to=settings.AUTH_USER_MODEL, verbose_name='autor da denúncia')),
            ],
            options={
                'verbose_name': 'denúncia',
                'verbose_name_plural': 'denúncias',
                'ordering': ('-created_at',),
            },
        ),
    ]
