# Generated by Django 5.2.17 on 2026-08-13 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('report_review', 'Análise de denúncia'), ('professional_review', 'Análise de profissional'), ('user_status', 'Alteração de conta'), ('notice_sent', 'Envio de aviso')], max_length=30, verbose_name='ação'),
        ),
        migrations.CreateModel(
            name='AdminAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('message', models.TextField(max_length=300, verbose_name='mensagem')),
                ('audience', models.CharField(choices=[('individual', 'Uma conta específica'), ('senior', 'Todas as pessoas idosas'), ('family', 'Todos os familiares'), ('professional', 'Todos os profissionais'), ('all', 'Todos os usuários não administrativos')], max_length=20, verbose_name='destinatários')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='quantidade de destinatários')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='administrador')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_admin_announcements', to=settings.AUTH_USER_MODEL, verbose_name='conta específica')),
            ],
            options={
                'verbose_name': 'aviso administrativo',
                'verbose_name_plural': 'avisos administrativos',
                'ordering': ('-created_at',),
            },
        ),
    ]
