# Generated by Django 5.2.17 on 2026-08-13 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100, verbose_name='profissão')),
                ('specialty', models.CharField(max_length=150, verbose_name='especialidade')),
                ('council', models.CharField(blank=True, help_text='Exemplo: CREFITO, COREN ou outro órgão aplicável.', max_length=50, verbose_name='conselho ou órgão profissional')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='número de registro')),
                ('service_region', models.CharField(default='Avaré-SP', max_length=150, verbose_name='região de atendimento')),
                ('service_mode', models.CharField(choices=[('volunteer', 'Somente voluntário'), ('paid', 'Somente remunerado'), ('both', 'Voluntário e remunerado')], default='both', max_length=20, verbose_name='modalidade de atendimento')),
                ('verification_status', models.CharField(choices=[('pending', 'Aguardando análise'), ('verified', 'Cadastro verificado'), ('needs_review', 'Revisão necessária')], default='pending', max_length=20, verbose_name='status da verificação')),
                ('verification_notes', models.TextField(blank=True, help_text='Visível apenas na administração.', verbose_name='observações administrativas')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verificado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profiles_verified', to=settings.AUTH_USER_MODEL, verbose_name='verificado por')),
            ],
            options={
                'verbose_name': 'perfil profissional',
                'verbose_name_plural': 'perfis profissionais',
                'constraints': [models.UniqueConstraint(condition=models.Q(models.Q(('council', ''), _negated=True), models.Q(('registration_number', ''), _negated=True)), fields=('council', 'registration_number'), name='professionals_unique_nonempty_credential')],
            },
        ),
    ]
