# Generated by Django 5.2.17 on 2026-08-13 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('category', models.CharField(choices=[('companionship', 'Companhia e convivência'), ('daily_tasks', 'Atividades do dia a dia'), ('transport', 'Transporte e deslocamento'), ('digital', 'Apoio com tecnologia'), ('wellbeing', 'Bem-estar e qualidade de vida'), ('other', 'Outra necessidade')], max_length=30, verbose_name='categoria')),
                ('description', models.TextField(max_length=800, verbose_name='descrição')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('resolved', 'Resolvida'), ('archived', 'Arquivada')], default='active', max_length=15, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to=settings.AUTH_USER_MODEL, verbose_name='pessoa idosa')),
            ],
            options={
                'verbose_name': 'necessidade',
                'verbose_name_plural': 'necessidades',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(help_text='Não informe documentos, senhas ou dados médicos desnecessários.', max_length=800, verbose_name='detalhes do pedido')),
                ('region', models.CharField(default='Avaré-SP', max_length=150, verbose_name='região do atendimento')),
                ('priority', models.CharField(choices=[('routine', 'Sem pressa'), ('soon', 'Preciso em breve')], default='routine', max_length=15, verbose_name='prazo')),
                ('preferred_service_mode', models.CharField(choices=[('volunteer', 'Somente voluntário'), ('paid', 'Somente remunerado'), ('both', 'Voluntário e remunerado')], default='both', max_length=20, verbose_name='modalidade preferida')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('accepted', 'Profissional aceito'), ('completed', 'Concluída'), ('canceled', 'Cancelada')], default='open', max_length=15, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='help_requests', to='needs.need', verbose_name='necessidade')),
            ],
            options={
                'verbose_name': 'solicitação de ajuda',
                'verbose_name_plural': 'solicitações de ajuda',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProfessionalInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='mensagem')),
                ('status', models.CharField(choices=[('pending', 'Aguardando resposta'), ('accepted', 'Aceito'), ('rejected', 'Recusado'), ('withdrawn', 'Retirado')], default='pending', max_length=15, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='respondido em')),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_interests', to='needs.helprequest', verbose_name='solicitação')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_interests', to=settings.AUTH_USER_MODEL, verbose_name='profissional')),
            ],
            options={
                'verbose_name': 'interesse profissional',
                'verbose_name_plural': 'interesses profissionais',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['status', '-created_at'], name='needs_helpr_status_3811bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='professionalinterest',
            constraint=models.UniqueConstraint(fields=('help_request', 'professional'), name='needs_unique_request_professional_interest'),
        ),
        migrations.AddConstraint(
            model_name='professionalinterest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('help_request',), name='needs_one_accepted_interest_per_request'),
        ),
    ]
