# Generated by Django 5.2.17 on 2026-08-13 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Aguardando autorização'), ('approved', 'Autorizado'), ('rejected', 'Recusado'), ('revoked', 'Revogado')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='respondido em')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links_as_family', to=settings.AUTH_USER_MODEL, verbose_name='familiar')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family_links_requested', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links_as_senior', to=settings.AUTH_USER_MODEL, verbose_name='pessoa idosa')),
            ],
            options={
                'verbose_name': 'vínculo familiar',
                'verbose_name_plural': 'vínculos familiares',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FamilyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_needs', models.BooleanField(default=False, verbose_name='visualizar necessidades')),
                ('can_view_requests', models.BooleanField(default=False, verbose_name='visualizar solicitações')),
                ('can_view_professional_interests', models.BooleanField(default=False, verbose_name='visualizar interesses profissionais')),
                ('can_receive_notifications', models.BooleanField(default=False, verbose_name='receber notificações de acompanhamento')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='relationships.familylink', verbose_name='vínculo')),
            ],
            options={
                'verbose_name': 'permissão familiar',
                'verbose_name_plural': 'permissões familiares',
            },
        ),
        migrations.AddConstraint(
            model_name='familylink',
            constraint=models.UniqueConstraint(fields=('senior', 'family'), name='relationships_unique_senior_family'),
        ),
    ]
