# Generated by Django 5.2.17 on 2026-08-13 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('family_link', 'Vínculo familiar'), ('help_request', 'Solicitação de ajuda'), ('professional_interest', 'Interesse profissional'), ('interest_response', 'Resposta ao interesse')], max_length=30, verbose_name='tipo')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('message', models.CharField(max_length=300, verbose_name='mensagem')),
                ('target_url', models.CharField(blank=True, max_length=250, verbose_name='destino')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lida em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notificatio_recipie_ce9d56_idx')],
            },
        ),
    ]
