# Generated by Django 5.2.17 on 2026-08-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('family_link', 'Vínculo familiar'), ('help_request', 'Solicitação de ajuda'), ('professional_interest', 'Interesse profissional'), ('interest_response', 'Resposta ao interesse'), ('report_update', 'Atualização de denúncia'), ('professional_review', 'Análise do perfil profissional'), ('account_status', 'Situação da conta')], max_length=30, verbose_name='tipo'),
        ),
    ]
